name: Android CI build and publish release APK

# on:
#   release:
#     types: [released]

on:
  push:
    branches:
      - master

env:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS:   "10406996"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Prepare system for use of sdkmanager
      run: |
        sudo apt-get --quiet update --yes
        sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 openjdk-17-jdk-headless
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        mkdir -p sdk/cmdline-tools
        unzip android-sdk.zip
        mv cmdline-tools sdk/cmdline-tools/latest

    - name: Set ANDROID_HOME and ANDROID_SDK_ROOT
      run: |
        echo "ANDROID_HOME=$PWD/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$PWD/sdk" >> $GITHUB_ENV
        echo "$PWD/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Verify SDK manager installation
      run: |
        type sdkmanager

    - name: Install Android SDK packages
      run: |
        echo y | sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
        echo y | sdkmanager "platform-tools" >/dev/null
        echo y | sdkmanager "emulator" >/dev/null
        echo y | sdkmanager "platform-tools" >/dev/null
        echo y | sdkmanager "tools" >/dev/null
        echo y | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
        set +o pipefail
        yes | sdkmanager --licenses
        set -o pipefail

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Create and Push Tag
      run: |
        TAG=$(date +v%Y%m%d-%H%M%S)
        git tag $TAG
        git push origin $TAG

    - name: Release APK
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
